### ISSUE TITLE
ls: cannot access '/dev/serial/by-id/*': No such file or directory

### ISSUE THREAD

**Issue by stigmat4j** [bigtreetech/Manta-M8P#109]
Manta m8p with CB1

```sudo dfu-util -d ,0483:df11 -R -a 0 -s 0x8000000:leave -D ./M8P_V2_H723_bootloader.bin``` after flashing bootloader i have message

```ls: cannot access '/dev/serial/by-id/*': No such file or directory```

**Comment by manotroll** [comment]
Any solution?
