### ISSUE TITLE
Documentation Fan port/RGB ratings

### ISSUE THREAD

**Issue by wizhippo** [bigtreetech/Manta-M8P#11]
The documentation says

12. The maximum output current of the fan port: 1A, Peak Value: 1.5A

Is this per fan port or in total?

Also for the RGB +5v.  What is it rating so we know how many leds we can drive?

**Comment by Exo7** [comment]
> The documentation says
> 
> 12. The maximum output current of the fan port: 1A, Peak Value: 1.5A
> 
> Is this per fan port or in total?
> 
> Also for the RGB +5v. What is it rating so we know how many leds we can drive?

as i can see on the schematic ;
Each FAN voltage output is protected by a 1A fuse. so i mean it's 1A by Fan Output.
For the RBG, the 5V line is protected by a 3.6A electronic fuse. 
but this line is shared with many other functions on board like logic, endstops, servo, probe, filament sensor, etc.. this is the main 5V line. 
i recommend to use external 5V power supply if you are looking to power daylight or chamber lighting, to keep safe the board in case of problem as there is no fuse between main 5V line and each outputs.
