### ISSUE TITLE
Manta M8P V2 -PWM / Tach-Pins swapped-

### ISSUE THREAD

**Issue by oMTEo** [bigtreetech/Manta-M8P#111]
While Im on setting up PWM-Fans on my new Manta-M8P-V2 I´ve found 2 wrong pin-definitions in the manual for FAN5 and FAN6.

PWM and Tacho-pins are swapped ! (I´ve cross-checked with the schematics)

Please check and correct all files and give me some salary for hours of exploring bugs on your products :)

![PWM-Tacho-Fan5+Fan6](https://github.com/bigtreetech/Manta-M8P/assets/132269070/8e7c5484-4321-46f0-80bc-e72e8330c06d)

**Comment by oMTEo** [comment]
Dear BTT, you forgot page 19...

![PWM-Tacho-Fan5+Fan6-Manual](https://github.com/bigtreetech/Manta-M8P/assets/132269070/e9892a09-064b-41c6-b41e-4083c41f9dc4)

**Comment by looxonline** [comment]
Fixed

**Comment by bigtreetech** [comment]
Docs updated. Thanks for pointing this out.
