### ISSUE TITLE
Audio Hat compatibility

### ISSUE THREAD

**Issue by KanduWorkshop** [bigtreetech/Manta-M8P#129]
If I am using the pi CM4, will any of the audio hats work? I was looking at the Raspberry Pi DigiAMP+, but i think the power supply may be an issue, i may look at the Raspberry Pi DAC (pro maybe) for this board if the Raspberry Pi DigiAMP+ power connection will not work and use a separate amplifier to run my speakers. I use audio queues from klipper if the printer cancels or has issues.

**Comment by bigtreetech** [comment]
The 40 pin GPIO output is according to the RPi standard so it should work. The PSU can supply around 1.5 - 2A of continuous current.
