### ISSUE TITLE
cannot access '/dev/serial/by-id': No such file or directory

### ISSUE THREAD

**Issue by hippieua** [bigtreetech/Manta-M8P#17]
release [V2.2.0](https://github.com/bigtreetech/CB1/releases/tag/V2.2.0)

[Hurakan_Debian11_Mainsail_kernel5.16_20220929.img.xz](https://github.com/bigtreetech/CB1/releases/download/V2.2.0/Hurakan_Debian11_Mainsail_kernel5.16_20220929.img.xz)

manta m8p board with CB1 module

biqu@BTT-CB1:~/klipper$ ls /dev/serial/by-id
ls: cannot access '/dev/serial/by-id': No such file or directory

biqu@BTT-CB1:~/klipper$ uname -a
Linux BTT-CB1 5.16.17-sun50iw9 #2.2.0 SMP Wed Sep 28 15:50:52 HKT 2022 aarch64 GNU/Linux

**Comment by hippieua** [comment]
bad connection CB1 to Manta M8P board. Just push it harder )

**Comment by wodier12** [comment]
what does "just push it harder mean?"

**Comment by hippieua** [comment]
> what does "just push it harder mean?"

laterally, just i just pushed cb1 harder to m8p until here it clicks in socket

**Comment by wodier12** [comment]
hmmmmm

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by wodier12** [comment]
" just push it harder " does not work, but thanks for trying...
