### ISSUE TITLE
OS Intermittently Freezing and Corrupting SD Card

### ISSUE THREAD

**Issue by 420noscope-exe** [bigtreetech/Manta-M8P#67]
I have a manta M8P mainboard with a CB1 installed onto it, running the provided klipper image.  I always leave my machine idling, powered on at all times.  Randomly, after about a week of idling, the web interface crashes.  I am unable to access it at all. 
 I cannot ssh into the device either.  The only solution is to unplug the printer and plug it back it.  This has a high probability of corrupting my SD card, and I've had to re-image it about 4 times now.  Where do I start with this?

**Comment by Peoplles** [comment]
Hello, I am having the same issue except it's daily.  What solution did you arrive at?

**Comment by 420noscope-exe** [comment]
@Peoplles https://github.com/bigtreetech/CB1/issues/125
