### ISSUE TITLE
Manta M8P V2.0 Schematics

### ISSUE THREAD

**Issue by olivbd** [bigtreetech/Manta-M8P#97]
Where can I find schematics for this board?

There are only schematics for V1.0 and V1.1.

**Comment by mykepredko** [comment]
I'm also looking for them.  

Please notify when they're available.

**Comment by mink007** [comment]
https://github.com/bigtreetech/Manta-M8P/blob/master/V2.0/Hardware/BIGTREETECH%20MANTA%20M8P%20V2.0-SCH.pdf

**Comment by olivbd** [comment]
> https://github.com/bigtreetech/Manta-M8P/blob/master/V2.0/Hardware/BIGTREETECH%20MANTA%20M8P%20V2.0-SCH.pdf

Thanks!!

I close this issue.
